# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Yidong Cai"
weight = 1

[zh-cn]
languageName = "中文"
languagedirection = "ltr"
title = "蔡益东"
weight = 2
[zh-cn.params.sidebar]
subtitle = "硕士在读，南京大学-计算机科学与技术系-媒体计算研究组"